### ISSUE TITLE
Empty templates.json is not created if it doesn't already exist

### ISSUE THREAD

**Issue by editf** [sanredz/DD2480-httpie#20]
I tried deleting `templates.json` and then running the commands for templates, which causes the following errors: 

**Create template:** `http template hej GET url a=b`
```
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/venv/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie', 'console_scripts', 'http')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/__main__.py", line 9, in main
    exit_status = main()
                  ^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 180, in main
    return raw_main(
           ^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 55, in raw_main
    store_json_template(args[1:])
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/cli/argtemplate.py", line 36, in store_json_template
    with open(TEMPLATE_FILE, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'httpie/cli/templates.json'
```

**Load template:** `http runt hej`
```
Traceback (most recent call last):
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/venv/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie', 'console_scripts', 'http')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/__main__.py", line 9, in main
    exit_status = main()
                  ^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 180, in main
    return raw_main(
           ^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 61, in raw_main
    args = load_template(args[1])
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/cli/argtemplate.py", line 87, in load_template
    with open(TEMPLATE_FILE, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'httpie/cli/templates.json'
```

**Edit template:** `http editt hej`
```
Traceback (most recent call last):
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/venv/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie', 'console_scripts', 'http')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/__main__.py", line 9, in main
    exit_status = main()
                  ^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 180, in main
    return raw_main(
           ^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 66, in raw_main
    edit_json_template(args[1:])
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/cli/argtemplate.py", line 52, in edit_json_template
    with open(TEMPLATE_FILE, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'httpie/cli/templates.json'
```

**Comment by mrporsev** [comment]
I wrote a fix to this issue, will commit and make pr in a second but here is the solution:
1. Deleted the file:
![image](https://user-images.githubusercontent.com/54756311/223437360-1166eac0-a3a0-4a2b-a224-0808011c6c02.png)


2. Run the command: 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/54756311/223437426-73488b8d-ea31-4123-be6c-cf073703d07d.png">

3. Check if file exists: 
![image](https://user-images.githubusercontent.com/54756311/223437509-84bc7a34-7db1-4501-99e6-9423e8492a77.png)

**Comment by mrporsev** [comment]
merged
