### ISSUE TITLE
Can't create a template with only URL parameter

### ISSUE THREAD

**Issue by editf** [sanredz/DD2480-httpie#24]
**Command run:** `http template test_template https://catfact.ninja/fact`
**Output:**
```
https://catfact.ninja/fact' is not a valid http method, defaulting to null...
Traceback (most recent call last):
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/venv/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie', 'console_scripts', 'http')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/__main__.py", line 9, in main
    exit_status = main()
                  ^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 180, in main
    return raw_main(
           ^^^^^^^^^
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/core.py", line 55, in raw_main
    store_json_template(args[1:])
  File "/Users/editflores/editf-github/dd2480/DD2480-httpie/httpie/cli/argtemplate.py", line 23, in store_json_template
    template_url = args.pop(0)
                   ^^^^^^^^^^^
IndexError: pop from empty list
```

**Comment by editf** [comment]
This will not be fixed since we decided to require a method parameter for all templates.
